source .env
# Export all environment variables so they are available to child scripts
export AWS_RDS_ENDPOINT
export AWS_RDS_DBNAME
export AWS_RDS_USER
export AWS_RDS_PASSWORD
export AWS_RDS_PORT
export AWS_REGION
export AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY
export S3_BUCKET_NAME
export MAC_LOCAL_IP
export POSTGRES_SCHEMA_TO_TRACK
export POSTGRES_TABLE_TO_TRACK
export REPLICATION_SLOT_NAME
export DEBEZIUM_CONNECTOR_VERSION
export S3_SINK_CONNECTOR_VERSION
export NAMESPACE
export REDPANDA_REPLICAS
export AWS_PROFILE    
