apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: cdc-project
  labels:
    app: kafka-connect
    component: cdc-pipeline
spec:
  type: NodePort
  ports:
  - name: rest-api
    port: 8083
    targetPort: 8083
    nodePort: 30083
    protocol: TCP
  selector:
    app: kafka-connect 